//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.RolesModels = new HashSet<RolesModel>();
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
            this.OvertimeModels = new HashSet<OvertimeModel>();
        }
    
        public System.Guid AccountId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesModel> RolesModels { get; set; }
        public virtual EmployeeModel EmployeeModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeModel> OvertimeModels { get; set; }
    }
}
