//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalHistoryModel
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ApprovalId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public int ApprovalLevel { get; set; }
        public Nullable<System.Guid> MaTrixId { get; set; }
        public string Type1 { get; set; }
        public string BrowseStatusID { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BrowseStatusModel BrowseStatusModel { get; set; }
        public virtual EmployeeModel EmployeeModel { get; set; }
        public virtual MaTrixFurloughModel MaTrixFurloughModel { get; set; }
        public virtual MatrixOvertimeModel MatrixOvertimeModel { get; set; }
        public virtual ConfirmWorkingTimeModel ConfirmWorkingTimeModel { get; set; }
        public virtual OvertimeModel OvertimeModel { get; set; }
        public virtual FurloughModel FurloughModel { get; set; }
    }
}
