//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmWorkingTimeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfirmWorkingTimeModel()
        {
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
        }
    
        public System.Guid ConfirmWorkingTimeID { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime Date1 { get; set; }
        public System.TimeSpan Time1 { get; set; }
        public string Type1 { get; set; }
        public string Reason { get; set; }
        public string BrowseStatusID { get; set; }
        public System.Guid CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public bool Disable1 { get; set; }
        public string ReasonStop { get; set; }
        public Nullable<bool> IsNightShift { get; set; }
        public Nullable<System.Guid> ShiftWorkId { get; set; }
        public Nullable<bool> TimekeepingFailed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
        public virtual BrowseStatusModel BrowseStatusModel { get; set; }
        public virtual EmployeeModel EmployeeModel { get; set; }
        public virtual ShiftWork ShiftWork { get; set; }
    }
}
