//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSpecialModel
    {
        public System.Guid EmployeeId { get; set; }
        public int Type1 { get; set; }
        public Nullable<bool> Late { get; set; }
        public Nullable<int> Minute1 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    
        public virtual EmployeeModel EmployeeModel { get; set; }
    }
}
