//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeModel()
        {
            this.EmployeeModel1 = new HashSet<EmployeeModel>();
            this.Accounts = new HashSet<Account>();
            this.OvertimeDetailModels = new HashSet<OvertimeDetailModel>();
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
            this.ConfirmWorkingTimeModels = new HashSet<ConfirmWorkingTimeModel>();
            this.FurloughModels = new HashSet<FurloughModel>();
            this.WorkdayEditModels = new HashSet<WorkdayEditModel>();
        }
    
        public System.Guid EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string FullName { get; set; }
        public string TimekeepingCode { get; set; }
        public bool Gender { get; set; }
        public System.Guid PositionID { get; set; }
        public string DateOfBirth { get; set; }
        public System.Guid EmployeeStatusCategoryId { get; set; }
        public System.Guid WorkPlaceID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public System.Guid ShiftWorkId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string PlaceOfBirth { get; set; }
        public string IdentityCard { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyEmail { get; set; }
        public string PersonalEmail { get; set; }
        public System.DateTime WorkingDate { get; set; }
        public double StandardWorkingDay { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime TrialJobFromDay { get; set; }
        public System.DateTime TrialJobEndDay { get; set; }
        public string TemporaryAddress { get; set; }
        public string HouseholdAddress { get; set; }
        public System.Guid BankId { get; set; }
        public string BankCardNumber { get; set; }
        public string BankBranch { get; set; }
        public string TaxId { get; set; }
        public string SocialinsuranceNumber { get; set; }
        public string RegistrationHospital { get; set; }
        public string Specialized { get; set; }
        public string DepartmentHint { get; set; }
        public Nullable<System.Guid> EducationId { get; set; }
        public Nullable<System.Guid> ReligionId { get; set; }
        public Nullable<System.Guid> FolkId { get; set; }
        public System.Guid NationalityId { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsHead { get; set; }
        public Nullable<double> RemainingLeavedays { get; set; }
        public Nullable<System.Guid> OvertimeCategoryId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Department Department { get; set; }
        public virtual Education Education { get; set; }
        public virtual EmployeeStatusCategory EmployeeStatusCategory { get; set; }
        public virtual Folk Folk { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Position Position { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual ShiftWork ShiftWork { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeModel> EmployeeModel1 { get; set; }
        public virtual EmployeeModel EmployeeModel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeDetailModel> OvertimeDetailModels { get; set; }
        public virtual OvertimeCategory OvertimeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmWorkingTimeModel> ConfirmWorkingTimeModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurloughModel> FurloughModels { get; set; }
        public virtual EmployeeSpecialModel EmployeeSpecialModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkdayEditModel> WorkdayEditModels { get; set; }
    }
}
