//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurloughModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FurloughModel()
        {
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
            this.FurloughDetailModels = new HashSet<FurloughDetailModel>();
        }
    
        public System.Guid FurloughId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public double NumberOfDaysOff { get; set; }
        public System.Guid LeaveCategoryId { get; set; }
        public string Reason { get; set; }
        public string ReasonStop { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string BrowseStatusID { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
        public virtual EmployeeModel EmployeeModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FurloughDetailModel> FurloughDetailModels { get; set; }
        public virtual BrowseStatusModel BrowseStatusModel { get; set; }
        public virtual LeaveCategory LeaveCategory { get; set; }
    }
}
