//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaTrixFurloughModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaTrixFurloughModel()
        {
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
        }
    
        public System.Guid MaTrixFurloughID { get; set; }
        public string MaTrixFurloughName { get; set; }
        public System.Guid DepartmentID { get; set; }
        public int FromDay { get; set; }
        public int ToDay { get; set; }
        public int ApprovalLevel { get; set; }
        public string ApprovalName { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
    }
}
