//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OvertimeModel()
        {
            this.ApprovalHistoryModels = new HashSet<ApprovalHistoryModel>();
            this.OvertimeDetailModels = new HashSet<OvertimeDetailModel>();
        }
    
        public System.Guid OvertimeId { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public string ProjectID { get; set; }
        public System.DateTime OvertimeDay { get; set; }
        public System.TimeSpan OvertimeStartTime { get; set; }
        public System.TimeSpan OvertimeEndTime { get; set; }
        public string Reason { get; set; }
        public string ReasonStop { get; set; }
        public string BrowseStatusID { get; set; }
        public Nullable<bool> Disable1 { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalHistoryModel> ApprovalHistoryModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OvertimeDetailModel> OvertimeDetailModels { get; set; }
        public virtual BrowseStatusModel BrowseStatusModel { get; set; }
        public virtual Department Department { get; set; }
    }
}
