//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageModel()
        {
            this.PagePermissionModels = new HashSet<PagePermissionModel>();
            this.FunctionModels = new HashSet<FunctionModel>();
        }
    
        public System.Guid PageId { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
        public System.Guid MenuId { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Visiable { get; set; }
        public Nullable<bool> isSystem { get; set; }
        public bool Actived { get; set; }
        public Nullable<bool> isQuickAccess { get; set; }
    
        public virtual MenuModel MenuModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagePermissionModel> PagePermissionModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionModel> FunctionModels { get; set; }
    }
}
