//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RalogNight
    {
        public System.Guid Id { get; set; }
        public string TimekeepingCode { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<bool> Del { get; set; }
        public string Note { get; set; }
    }
}
