//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftWork()
        {
            this.EmployeeModels = new HashSet<EmployeeModel>();
            this.ConfirmWorkingTimeModels = new HashSet<ConfirmWorkingTimeModel>();
            this.WorkdayEditModels = new HashSet<WorkdayEditModel>();
        }
    
        public System.Guid ShiftWorkId { get; set; }
        public string ShiftWorkCode { get; set; }
        public string ShiftWorkName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTimeBetweenShift { get; set; }
        public System.TimeSpan StartTimeBetweenShift { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.TimeSpan OvertimeStartTime { get; set; }
        public double TotalWorkTime { get; set; }
        public int NumberMinuteLate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public double StandardHour { get; set; }
        public bool IsNightShift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeModel> EmployeeModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmWorkingTimeModel> ConfirmWorkingTimeModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkdayEditModel> WorkdayEditModels { get; set; }
    }
}
