//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkdayEditModel
    {
        public System.Guid ID { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.DateTime Date1 { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public string WorkTime { get; set; }
        public string OT { get; set; }
        public string OTAfter22h { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> LastModifiedAccountId { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> IsNightShift { get; set; }
        public Nullable<System.Guid> ShiftWorkId { get; set; }
    
        public virtual EmployeeModel EmployeeModel { get; set; }
        public virtual ShiftWork ShiftWork { get; set; }
    }
}
